name: Build & Publish Docker image

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'examples/**'
    tags:
      - '1.6.*'

jobs:
  build:
    name: Build multiplatform image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: php-apache
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bjalbor/wbce:latest,bjalbor/wbce:1.6.3
